// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlapi

import (
	"git.zjuvis.org/rnvis/bus-routing-backend/pkg/stationgraph"
)

type AfterGraphBuilt struct {
	Graph    *stationgraph.StationGraph `json:"graph"`
	Username string                     `json:"username"`
}

type ExistBusRoute struct {
	ID       int    `json:"id"`
	Name     string `json:"name"`
	Stations []int  `json:"stations"`
}

type NewRoutePlanning struct {
	OriginID int `json:"originId"`
	DestID   int `json:"destId"`
}

type NewStationGraph struct {
	Origin int   `json:"origin"`
	Dest   int   `json:"dest"`
	Stops  []int `json:"stops"`
}
